spring:
  profiles:
    active:
      - dev
      
      
---        
spring:
  profiles: dev  #开发环境
  application:
    name: microsevicecloud-config-auguigu-dev-dd
    
   
---
spring:
  profiles: test  #开发环境
  application:
    name: microsevicecloud-config-auguigu-test-vv 
