spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
  
spring:
  profiles: dev
  application:
    name:  microservicecloud-config-dept-client
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource           #当前数据源操作类型
   driver-class-name: org.gjt.mm.mysql.Driver             #mysq1驱动包
   url: jdbc:mysql://127.0.0.1:3306/cloudDB01?useUnicode=true&characterEncoding=UTF-8             #数据库名称
   username: root
   password: 123456
   dbcp2:
    min-idle : 5                                          #数据库连接池的最小维持连接数
    initial-size: 5                                       #初始化连接数
    max-total: 5                                           #最大连接数
    max-wait-millis: 200    
    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #mybatis配置文件所在路径
  type-aliases-package:  com.atguigu.springcloud.entities     #所有 Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                         # mapper映射文件
 


eureka:
  client: #客户端注册进eureka服务列表
   service-url:   #defaultZone: http://eureka7001:7001/eureka/  单机版是，现在是集群看下面配置
      defaultZone: http://eureka7001.com:7001/eureka/ # 自定义服务器名称信息
  instance:
    instance-id: dept-8001.com  #访问路径可以显示IP地址
    prefer-ip-address:  true  #访问路径可以显示自己的IP地址  
  

info:
  app.name: atguigu-microservicecloud-springcloudfig01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$











---


server:
  port: 8001
  
spring:
  profiles: test
  application:
    name:  microservicecloud-config-dept-client
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource           #当前数据源操作类型
   driver-class-name: org.gjt.mm.mysql.Driver             #mysq1驱动包
   url: jdbc:mysql://127.0.0.1:3306/cloudDB02?useUnicode=true&characterEncoding=UTF-8             #数据库名称
   username: root
   password: 123456
   dbcp2:
    min-idle : 5                                          #数据库连接池的最小维持连接数
    initial-size: 5                                       #初始化连接数
    max-total: 5                                           #最大连接数
    max-wait-millis: 200    
    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #mybatis配置文件所在路径
  type-aliases-package:  com.atguigu.springcloud.entities     #所有 Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                         # mapper映射文件
 


eureka:
  client: #客户端注册进eureka服务列表
   service-url:   #defaultZone: http://eureka7001:7001/eureka/  单机版是，现在是集群看下面配置
      defaultZone: http://eureka7001.com:7001/eureka/ # 自定义服务器名称信息
  instance:
    instance-id: dept-8001.com  #访问路径可以显示IP地址
    prefer-ip-address:  true  #访问路径可以显示自己的IP地址  
  

info:
  app.name: atguigu-microservicecloud-springcloudfig02
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
